comment_width = 120
max_width = 160
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20
fn_args_layout = "Compressed"
indent_style = "Visual"
where_single_line = true
fn_single_line = true